name: Bug report
description: Reportá un bug
labels: ["bug", "help wanted"]
body:
  - type: textarea
    attributes:
      label: Qué pasó
      description: Contanos qué esperabas y qué obtuviste
    validations:
      required: true
  - type: textarea
    attributes:
      label: Pasos para reproducir
    validations:
      required: true
  - type: textarea
    attributes:
      label: Archivo(s) .erdplus (si podés)
