name: Feature request
description: Pedí una mejora
labels: ["enhancement", "good first issue"]
body:
  - type: textarea
    attributes:
      label: Qué te gustaría
    validations:
      required: true
