/**
 * Export templates with Erdus branding
 * Part of Erdus - Universal ER Diagram Converter
 * @author tobiager
 */

interface TemplateVars {
  timestamp: string;
  author: string;
  language: string;
  diagramName: string;
  description: string;
}

export const EXPORT_TEMPLATES = {
  sql: `-- ================================================
-- Generated with Erdus - Universal ER Diagram Converter
-- Repository: https://github.com/tobiager/Erdus
-- ================================================
-- Generated on: {timestamp}
-- Generated by: {author}
-- Language: {language}
-- Diagram: {diagramName}
-- Description: {description}
-- 
-- Erdus is an open-source universal ER diagram converter
-- Convert between SQL, TypeORM, Prisma, Sequelize and more!
-- Visit: https://github.com/tobiager/Erdus
-- ================================================

`,
  
  typeorm: `/**
 * Generated with Erdus - Universal ER Diagram Converter
 * Repository: https://github.com/tobiager/Erdus
 * 
 * Generated on: {timestamp}
 * Generated by: {author}
 * Diagram: {diagramName}
 * 
 * Erdus - Convert between SQL, TypeORM, Prisma, Sequelize and more!
 * Visit: https://github.com/tobiager/Erdus
 */

`,

  prisma: `// Generated with Erdus - Universal ER Diagram Converter
// Repository: https://github.com/tobiager/Erdus
// Generated on: {timestamp}
// Generated by: {author}
// Diagram: {diagramName}
//
// Erdus - Convert between SQL, TypeORM, Prisma, Sequelize and more!
// Visit: https://github.com/tobiager/Erdus

`,

  dbml: `// Generated with Erdus - Universal ER Diagram Converter
// Repository: https://github.com/tobiager/Erdus
// Generated on: {timestamp}
// Generated by: {author}
// Diagram: {diagramName}
//
// Erdus - Convert between SQL, TypeORM, Prisma, Sequelize and more!
// Visit: https://github.com/tobiager/Erdus

`,

  mermaid: `%% Generated with Erdus - Universal ER Diagram Converter
%% Repository: https://github.com/tobiager/Erdus
%% Generated on: {timestamp}
%% Generated by: {author}
%% Diagram: {diagramName}
%%
%% Erdus - Convert between SQL, TypeORM, Prisma, Sequelize and more!
%% Visit: https://github.com/tobiager/Erdus

`
};

/**
 * Format export template with provided variables
 */
export function formatExportTemplate(
  format: keyof typeof EXPORT_TEMPLATES,
  vars: Partial<TemplateVars>
): string {
  const template = EXPORT_TEMPLATES[format] || '';
  
  const defaults: TemplateVars = {
    timestamp: new Date().toISOString(),
    author: 'tobiager',
    language: 'default',
    diagramName: 'Untitled Diagram',
    description: ''
  };
  
  const finalVars = { ...defaults, ...vars };
  
  return template
    .replace(/\{timestamp\}/g, finalVars.timestamp)
    .replace(/\{author\}/g, finalVars.author)
    .replace(/\{language\}/g, finalVars.language)
    .replace(/\{diagramName\}/g, finalVars.diagramName)
    .replace(/\{description\}/g, finalVars.description);
}
